### PR TITLE
Fix active file sort and `displayed_listing`

### LINKED ISSUE #4326: Make active_file_sort in ProjectStore memo-izeable
`active_file_sort` returns new javascript object every time it's called. That means you can't check if it's the same value (without looking deeper), defeating any performance optimizations that using immutable.js is all about.

Related: #4325

### PR DESCRIPTION
**Pull request by johnjeng**
# Description
Fixes #4326

Also makes it so that `displayed_listing` is correctly recomputed only when its args are changed.

# Testing Steps
1. Change the file sort in a project
1. Change the default file sort in account settings
1. Open a new project, the sort should be that default
1. The project from step 1 should have the same sorting
1. In the browser console, run `smc.redux.getProjectStore(project_id).selectors.stripped_public_paths.fn.recomputations();` with `project_id` appropriately filled in.
1. Select some files
1. Run the same code above. The result should not have increased.
1. Toggle displaying masked files, that should work
1. Filter by searching. That should work too.
1. Recomputations should have increased.

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [ ] Run eslint on new and edited files
- [x] All new code is actually used.
- [x] Non-obvious code has some sort of comments.

Front end:
- [x] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [x] Completely restart Webpack with `./w` in `/src`
- [x] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

File: src/smc-webapp/app-framework/TypedMap.ts [hunk 1]
```diff
@@ -119,7 +119,7 @@ interface TypedMapFactory<TProps extends Record<string, any>> {
   new (values: TProps): TypedMap<TProps>;
 }
 
-export function typedMap<TProps extends object>(
+export function TypedMap<TProps extends object>(
```
Comment (johnjeng) [inline src/smc-webapp/app-framework/TypedMap.ts]: Follow immutable.js's convention that the type is also the function to create one.

File: src/smc-webapp/project/explorer/explorer.tsx [hunk 2]
```diff
@@ -153,7 +153,7 @@ export const Explorer = rclass<ReactProps>(
         },
 
         [name]: {
-          active_file_sort: rtypes.object,
+          active_file_sort: rtypes.immutable.Map,
```
Comment (johnjeng) [inline src/smc-webapp/project/explorer/explorer.tsx]: Important because of our auto-conversion code!

File: src/smc-webapp/project_actions.ts [hunk 3]
```diff
@@ -1657,12 +1657,14 @@ export class ProjectActions extends Actions<ProjectStoreState> {
...
-      is_descending = !current.is_descending;
+    if (current.get("column_name") === column_name) {
+      is_descending = !current.get("is_descending");
     } else {
       is_descending = false;
     }
-    const next_file_sort = { is_descending, column_name };
+    const next_file_sort = current
+      .set("is_descending", is_descending)
+      .set("column_name", column_name);
```
Comment (johnjeng) [inline src/smc-webapp/project_actions.ts]: The performance hit is negligible.

File: src/smc-webapp/project_store.ts [hunk 4]
```diff
@@ -248,6 +249,13 @@ export class ProjectStore extends Store<ProjectStoreState> {
       show_library: false,
       show_new: false,
       file_listing_scroll_top: undefined,
+      active_file_sort: TypedMap({
+        is_descending: false,
+        column_name:
+          redux
+            .getStore("account")
+            ?.getIn(["other_settings", "default_file_sort"]) ?? "time"
+      }),
```
Comment (johnjeng) [inline src/smc-webapp/project_store.ts]: Always have a sort order defined.

File: src/smc-webapp/project_store.ts [hunk 5]
```diff
@@ -286,21 +294,6 @@ export class ProjectStore extends Store<ProjectStoreState> {
...
-          const is_descending = false;
-          const column_name = (this.redux.getStore("account") as any).getIn([
-            "other_settings",
-            "default_file_sort"
-          ]);
-          return { is_descending, column_name };
-        }
-      }
-    },
-
```
Comment (johnjeng) [inline src/smc-webapp/project_store.ts]: This relied on `getIn([arg])` and `get(arg)` having two different behaviors. Definitely an abstraction leak. See #4325.
