### PR TITLE
frontend/admin/license: fix expire date field 

### LINKED ISSUE #8559: admin/license: can't set expiration field
When I create a license as admin and set an expiration, I get this error:

> Error: postgresql error: invalid input syntax for type timestamp: "{"$L":"en","$d":"2025-09-29T22:00:00.000Z","$y":2025,"$M":8,"$D":30,"$W":2,"$H":0,"$m":0,"$s":0,"$ms":0,"$x":{},"$isDayjsObject":true}"

### PR DESCRIPTION
**Pull request by haraldschilly**
This fixes #8559 by sending the string of the date to postgres. the day.js object does not work.

### CODE REVIEW

File: src/packages/frontend/site-licenses/admin/license.tsx [hunk 1]
```diff
@@ -35,7 +35,7 @@ import { actions } from "./actions";
 import { Managers } from "./managers";
 import Owner from "./owner";
 import { DisplayQuota, EditQuota } from "./quota";
-import { license_fields, license_field_type, ManagerInfo } from "./types";
+import { license_field_type, license_fields, ManagerInfo } from "./types";
```
Comment (williamstein) [inline src/packages/frontend/site-licenses/admin/license.tsx:38]: Why is this switched?  Is it some sort of linting?  It's true that the new order is better since it is alphabetical, but it's a surprising thing for a non-linter to actual change.

File: src/packages/frontend/site-licenses/admin/license.tsx [hunk 2]
```diff
@@ -142,6 +142,12 @@ export const License: React.FC<Props> = (props: Props) => {
     actions.set_edit(license.get("id"), field, new_val);
   }
 
+  function on_date_change(field, _date, dateString): void {
+    // For date fields, use the dateString instead of the Day.js object
+    // to ensure proper serialization for PostgreSQL
+    actions.set_edit(license.get("id"), field, dateString || null);
```
Comment (williamstein) [inline src/packages/frontend/site-licenses/admin/license.tsx:148]: Why use `dateString || null` instead of `dateString ?? null` which seems more idiomatic in modern times.  Who uses || anymore?

**Comment by williamstein** [comment]
**This code is weird.**  Every single change just seems weird.

File: src/packages/frontend/site-licenses/admin/license.tsx (hunk 1 above)
Comment (haraldschilly) [reply src/packages/frontend/site-licenses/admin/license.tsx:38]: all imports are sorted by vs code.

File: src/packages/frontend/site-licenses/admin/license.tsx (hunk 2 above)
Comment (haraldschilly) [reply src/packages/frontend/site-licenses/admin/license.tsx:148]: So, there is an issue, where unsetting the expire date field does not set it to null in the database. The idea is to send a "null" value instead of an empty string. Doesn't work, though.
