### PR TITLE
Persist grading

### LINKED ISSUE #3049: when grade is entered it sometimes vanishes from the form
Reported by Gabriela Dorfman Furman:

In a course, after distributing an assignment:
1. Click the "Collect .." button (task)
1. Try to write in the window under the caption "Enter Grade" (where it says "Grade (any text) ...")
1. After a few seconds the grade is deleted (like nothing is written) or the save button does not work

Sometimes, if the bug does not appear at first, you can hit tab to enter a comment, then shift-tab to go back and enter new text for the grade, and _that_ grade vanishes after a second or so.

Seen with browsers: 
- Chrome 67 on Windows
- Safari 11.0.3 on macOS

May be related to #2928 - grade & comments are not retained on tabbing away and back.

### PR DESCRIPTION
**Pull request by johnjeng**
Persist grading assignments and fix #3049.

### CODE REVIEW

File: src/smc-webapp/course/actions.ts [hunk 1]
```diff
@@ -1492,42 +1497,104 @@ export class CourseActions extends Actions<CourseState> {
...
-    grades[student.get("student_id")] = grade;
-    (obj as any).grades = grades;
-    this._set(obj);
-  }
 
-  set_comments(assignment, student, comments) {
-    let left;
+    const open_grades = store.get("active_feedback_edits");
+    const new_open_grades = open_grades.delete(
+      assignment.get("assignment_id") + student.get("student_id")
```
Comment (haraldschilly) [inline src/smc-webapp/course/actions.ts]: I'm curious. Should this line maybe call `utils::assignment_identifier` to semantically express that this is the common key used everywhere?

Comment (johnjeng) [reply src/smc-webapp/course/actions.ts]: Oh, yup. Missed that one.

File: src/smc-webapp/course/actions.ts [hunk 2]
```diff
@@ -1544,14 +1544,14 @@ export class CourseActions extends Actions<CourseState> {
...
+    let comments: string;
     if (new_edited_comments != undefined) {
       comments = new_edited_comments;
     } else if (current_edited_comments != undefined) {
       comments = current_edited_comments;
     } else {
-      comments = store.get_comments(assignment, student) || ""
-
+      comments = store.get_comments(assignment, student) || "";
+    }
```
Comment (johnjeng) [inline src/smc-webapp/course/actions.ts]: This got deleted somehow. Oops.
