### PR TITLE
Fix Mentions Image Pasting

### LINKED ISSUE #3674: mentions bug -- use @mention and paste an image results in mangled HTML
Screenshot 2019-03-09 at 9 40 36 AM

```
<span class<img src=".chat-images/Screenshot 2019-03-09 at 9.37.05 AM.png" 
width='30%'>="user-mention">@John Jeng</span> 
```

The above mangled mess it what happens when you:

1. Type "@John Jeng" and hit return, then
2. Paste in an image.

The html for the mention gets mangled up with the html for the image.

### PR DESCRIPTION
**Pull request by johnjeng**
# Description
Fix #3674 
Fix styling for file uploads in the chat dropzone.

Also add additional instructions below the chat box.

# Testing Steps
1. Add some mentions to chat
1. Paste in an image into 
   1. Beginning of the text
   1. Inside the first half of a mention
   1. Inside the second half of a mention
   1. Inside the last mention
   1. After the last mention but before the rest of the text
   1. At the very end of the text
1. Paste a second image into the same locations

# Relevant Issues

### [Checklist](https://github.com/sagemathinc/cocalc/wiki/PR-Checklist):
- [x] No debugging console.log messages.
- [x] All new code is actually used.
- [x] Non-obvious code has some sort of comments.

Front end:
- [x] Restart at least one project and check its `~/.smc/local_hub/local_hub.log`
- [x] Completely restart Webpack with `./w` in `/src`
- [x] Completely restart the hub by killing and restarting `./start_hub.py` in `/src/dev/project`
- [ ] Screenshots if relevant.

### CODE REVIEW

File: src/smc-webapp/chat/store.ts [hunk 1]
```diff
@@ -4,6 +4,14 @@ import * as immutable from "immutable";
 // Internal Libraries
 import { Store } from "../app-framework/Store";
 
+export type MentionList = immutable.List<{
```
Comment (williamstein) [inline src/smc-webapp/chat/store.ts]: Oh, I didn't realize you could do that with immutable.List and typescript.  Good to know!

**Comment by williamstein** [comment]
Code looks good to me; now trying it out.
